### ISSUE TITLE
NixOS error when setting programs.sway.package = pkgs.swayfx

### ISSUE THREAD

**Issue by WillPower3309** [WillPower3309/swayfx#161]
Setting `programs.sway.package = pkgs.swayfx` in a Nix config will result in the following error:

```sh
error: Package, 'swayfx-0.2', did not specify any session names, as strings, in
       'passthru.providedSessions'. This is required when used as a session package.

       The session names can be looked up in:
         /nix/store/704ch74d0hh687ai5idcrwix3xcdwgn9-swayfx-0.2/share/xsessions
         /nix/store/704ch74d0hh687ai5idcrwix3xcdwgn9-swayfx-0.2/share/wayland-sessions
(use '--show-trace' to show detailed location information)
```

The swayfx nix package definition should include this session name

**Comment by vegaelle** [comment]
Is there a workaround to make it work currently?

**Comment by TotalChaos05** [comment]
it worked for me without needing that, is it fixed now?

**Comment by TotalChaos05** [comment]
it works in the home-manager module, not sure about the nixos option

**Comment by WillPower3309** [comment]
> it worked for me without needing that, is it fixed now?

Were you using home-manager? Looks like it still isn't working

**Comment by TotalChaos05** [comment]
I was, but i also made a test flake without it

**Comment by name-snrl** [comment]
If https://github.com/NixOS/nixpkgs/pull/267261 and https://github.com/NixOS/nixpkgs/pull/267261 are merged, it will be solved

**Comment by WillPower3309** [comment]
> If https://github.com/NixOS/nixpkgs/pull/267261 and https://github.com/NixOS/nixpkgs/pull/267261 are merged, it will be solved

Thanks for getting a fix up on the nix side! I think you may have linked the same PR twice

**Comment by name-snrl** [comment]
> twice

Oops, https://github.com/NixOS/nixpkgs/pull/234243

**Comment by TLATER** [comment]
AIUI, those will fix the issue upstream in nixpkgs, but the flake in this repository still needs to be updated. Don't think much can be done until the dust settles on how sway forks will be used by the nixpkgs module, though.

**Comment by kira-bruneau** [comment]
This should be fixed now since https://github.com/NixOS/nixpkgs/pull/270013 was merged!

**Comment by RicArch97** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/270013

**Comment by WillPower3309** [comment]
> This should be fixed now since https://github.com/NixOS/nixpkgs/pull/270013 was merged!
> 
> **EDIT:** Oops spoke to soon, still need https://github.com/NixOS/nixpkgs/pull/267261

Thanks a ton for helping out! I'll monitor that pull request

**Comment by RicArch97** [comment]
Fixed in https://github.com/NixOS/nixpkgs/pull/273762. Tested in my own config, and setting `programs.sway.package = pkgs.swayfx` now correctly wraps the binary, which fixes the session error.

**Comment by name-snrl** [comment]
> Tested in my own config

idk what you're talking about, hardcoded is still present in the module:

https://github.com/NixOS/nixpkgs/blob/b21d62223e01fa300390b7fe5531bc664b34fc99/nixos/modules/programs/wayland/sway.nix#L29-L56

This means that if you export some variable in `programs.sway.extraSessionCommands`, for example, it will not appear in your env.

**Comment by eclairevoyant** [comment]
You can override it yourself in the .package option instead.

**Comment by name-snrl** [comment]
> option instead

I know, but what the reason to use module then?

**Comment by RicArch97** [comment]
> idk what you're talking about, hardcoded is still present in the module

The change fixed the problem described in this issue. It's true that the module needs a change as well, but that's a different issue imo

**Comment by RicArch97** [comment]
Now **really** resolved with https://github.com/NixOS/nixpkgs/pull/267261 merged 🎉

**Comment by WillPower3309** [comment]
Big thanks to @kira-bruneau and @name-snrl for getting this in nixpkgs! Happy to announce this is completed :)

**Comment by Raagh** [comment]
I am still encountering this with a newer version of the package
`
       error: Package, 'swayfx-0.3.2', did not specify any session names, as strings, in
       'passthru.providedSessions'. This is required when used as a session package.

       The session names can be looked up in:
         /nix/store/38j434zdrdzkixp1d81flfrhpzz3y1p1-swayfx-0.3.2/share/xsessions
         /nix/store/38j434zdrdzkixp1d81flfrhpzz3y1p1-swayfx-0.3.2/share/wayland-sessions
`
the override workaround works but I am curious if this is a regression or am I doing something wrong.

`
  programs.sway = {
    enable = true;
    package = pkgs.swayfx;
    wrapperFeatures.gtk = true;
  };
`
