### ISSUE TITLE
Error: Transaction test error when trying to install swayfx on Fedora Linux 37

### ISSUE THREAD

**Issue by AlvaroParker** [WillPower3309/swayfx#49]
- **Swayfx Version:**
  - `0.1-1.fc37`

- **Debug Log:**
```
➜  sudo dnf install swayfx                                            
Dependencies resolved.
==========================================================================================
 Package                    Arch   Version       Repository                          Size
==========================================================================================
Installing:
 swayfx                     x86_64 0.1-1.fc37    copr:copr.fedorainfracloud.org:swayfx:swayfx
                                                                                    365 k
Installing dependencies:
 fcft                       x86_64 3.1.5-1.fc37  fedora                              72 k
 libseat                    x86_64 0.7.0-2.fc37  fedora                              28 k
 python3-dbus-next          noarch 0.2.3-4.fc37  fedora                             154 k
 python3-i3ipc              noarch 2.2.1-6.fc37  fedora                              71 k
 python3-psutil             x86_64 5.9.1-1.fc37  fedora                             271 k
 python3-tenacity           noarch 8.0.1-6.fc37  fedora                              60 k
 python3-xlib               noarch 0.31-5.fc37   fedora                             351 k
 sway                       x86_64 1.7-3.fc37    fedora                             366 k
 swaybg                     x86_64 1.1.1-2.fc37  fedora                              24 k
 utf8proc                   x86_64 2.7.0-3.fc37  fedora                              80 k
 wlroots                    x86_64 0.15.1-4.fc37 fedora                             319 k
Installing weak dependencies:
 desktop-backgrounds-compat noarch 37.0.0-4.fc37 updates                            9.0 k
 dmenu                      x86_64 5.1-2.fc37    fedora                              31 k
 foot                       x86_64 1.13.1-1.fc37 fedora                             305 k
 foot-terminfo              x86_64 1.13.1-1.fc37 fedora                              12 k
 sway-systemd               noarch 0.2.2-2.fc37  fedora                              18 k
 swayidle                   x86_64 1.7.1-2.fc37  fedora                              27 k
 swaylock                   x86_64 1.6-2.fc37    fedora                              42 k

Transaction Summary
==========================================================================================
Install  19 Packages

Total download size: 2.5 M
Installed size: 8.0 M
Is this ok [Y/n]: 
Downloading Packages:
(1/19): dmenu-5.1-2.fc37.x86_64.rpm                       133 kB/s |  31 kB     00:00    
(2/19): fcft-3.1.5-1.fc37.x86_64.rpm                      238 kB/s |  72 kB     00:00    
(3/19): foot-terminfo-1.13.1-1.fc37.x86_64.rpm            156 kB/s |  12 kB     00:00    
(4/19): libseat-0.7.0-2.fc37.x86_64.rpm                   370 kB/s |  28 kB     00:00    
(5/19): swayfx-0.1-1.fc37.x86_64.rpm                      685 kB/s | 365 kB     00:00    
(6/19): foot-1.13.1-1.fc37.x86_64.rpm                     1.0 MB/s | 305 kB     00:00    
(7/19): python3-dbus-next-0.2.3-4.fc37.noarch.rpm         999 kB/s | 154 kB     00:00    
(8/19): python3-tenacity-8.0.1-6.fc37.noarch.rpm          780 kB/s |  60 kB     00:00    
(9/19): python3-psutil-5.9.1-1.fc37.x86_64.rpm            1.7 MB/s | 271 kB     00:00    
(10/19): sway-1.7-3.fc37.x86_64.rpm                       3.9 MB/s | 366 kB     00:00    
(11/19): python3-i3ipc-2.2.1-6.fc37.noarch.rpm            236 kB/s |  71 kB     00:00    
(12/19): python3-xlib-0.31-5.fc37.noarch.rpm              2.1 MB/s | 351 kB     00:00    
(13/19): sway-systemd-0.2.2-2.fc37.noarch.rpm             235 kB/s |  18 kB     00:00    
(14/19): swaybg-1.1.1-2.fc37.x86_64.rpm                   319 kB/s |  24 kB     00:00    
(15/19): swayidle-1.7.1-2.fc37.x86_64.rpm                 356 kB/s |  27 kB     00:00    
(16/19): swaylock-1.6-2.fc37.x86_64.rpm                   538 kB/s |  42 kB     00:00    
(17/19): utf8proc-2.7.0-3.fc37.x86_64.rpm                 1.0 MB/s |  80 kB     00:00    
(18/19): wlroots-0.15.1-4.fc37.x86_64.rpm                 3.8 MB/s | 319 kB     00:00    
(19/19): desktop-backgrounds-compat-37.0.0-4.fc37.noarch. 122 kB/s | 9.0 kB     00:00    
------------------------------------------------------------------------------------------
Total                                                     911 kB/s | 2.5 MB     00:02     
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  file /etc/sway/config conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/bin/sway conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/bin/swaybar conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/bin/swaymsg conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/bin/swaynag conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man1/sway.1.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man1/swaymsg.1.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man1/swaynag.1.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man5/sway-bar.5.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man5/sway-input.5.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man5/sway-output.5.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man5/sway.5.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man5/swaynag.5.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man7/sway-ipc.7.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man7/swaybar-protocol.7.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
```
 

- **Description:**
    - I enabled the copr repo doing `sudo yum copr enable  swayfx/swayfx ` then I did `sudo dnf update --refresh` followed by `sudo dnf install swayfx`. Seems that I can't install swayfx because two packages are providing the same file names?

**Comment by WillPower3309** [comment]
Do you currently have vanilla sway installed?

**Comment by WillPower3309** [comment]
Hmm, curious. Good to know! Tagging @ErikReider for visibility here

**Comment by WillPower3309** [comment]
> @WillPower3309 It looks like the issue is that it recommends `sway-systemd`, which requires sway.

Yup, that'd be it! Taking a look now :)

**Comment by WillPower3309** [comment]
Will be closed pending resolution of a related actions issue

**Comment by WillPower3309** [comment]
Should work now!

**Comment by AlvaroParker** [comment]
@WillPower3309  after waiting a day just in case the changes would take some time to upload, the problem persists.

**Comment by WillPower3309** [comment]
> @WillPower3309  after waiting a day just in case the changes would take some time to upload, the problem persists. 

Apologies for this issue, I'll take another look at fixing it this evening

**Comment by ErikReider** [comment]
Is it the exact same output? I'm not having an issue on my laptop on f37

**Comment by AlvaroParker** [comment]
@ErikReider Looks like it. I'll paste it just in case.
```
➜  sudo dnf install swayfx                                                                                                                                                                      
Dependencies resolved.
===================================================================================================================================================================================================================
 Package                                               Architecture                      Version                                     Repository                                                               Size
===================================================================================================================================================================================================================
Installing:
 swayfx                                                x86_64                            0.1-1.fc37                                  copr:copr.fedorainfracloud.org:swayfx:swayfx                            365 k
Installing dependencies:
 fcft                                                  x86_64                            3.1.5-1.fc37                                fedora                                                                   72 k
 libseat                                               x86_64                            0.7.0-2.fc37                                fedora                                                                   28 k
 python3-dbus-next                                     noarch                            0.2.3-4.fc37                                fedora                                                                  154 k
 python3-i3ipc                                         noarch                            2.2.1-6.fc37                                fedora                                                                   71 k
 python3-psutil                                        x86_64                            5.9.1-1.fc37                                fedora                                                                  271 k
 python3-tenacity                                      noarch                            8.0.1-6.fc37                                fedora                                                                   60 k
 python3-xlib                                          noarch                            0.31-5.fc37                                 fedora                                                                  351 k
 sway                                                  x86_64                            1.7-3.fc37                                  fedora                                                                  366 k
 swaybg                                                x86_64                            1.1.1-2.fc37                                fedora                                                                   24 k
 utf8proc                                              x86_64                            2.7.0-3.fc37                                fedora                                                                   80 k
 wlroots                                               x86_64                            0.15.1-4.fc37                               fedora                                                                  319 k
Installing weak dependencies:
 desktop-backgrounds-compat                            noarch                            37.0.0-4.fc37                               updates                                                                 9.0 k
 dmenu                                                 x86_64                            5.1-2.fc37                                  fedora                                                                   31 k
 foot                                                  x86_64                            1.13.1-1.fc37                               fedora                                                                  305 k
 foot-terminfo                                         x86_64                            1.13.1-1.fc37                               fedora                                                                   12 k
 sway-systemd                                          noarch                            0.2.2-2.fc37                                fedora                                                                   18 k
 swayidle                                              x86_64                            1.7.1-2.fc37                                fedora                                                                   27 k
 swaylock                                              x86_64                            1.6-2.fc37                                  fedora                                                                   42 k

Transaction Summary
===================================================================================================================================================================================================================
Install  19 Packages

Total download size: 2.5 M
Installed size: 8.0 M
Is this ok [Y/n]: 
Downloading Packages:
(1/19): dmenu-5.1-2.fc37.x86_64.rpm                                                                                                                                                137 kB/s |  31 kB     00:00    
(2/19): fcft-3.1.5-1.fc37.x86_64.rpm                                                                                                                                               230 kB/s |  72 kB     00:00    
(3/19): foot-terminfo-1.13.1-1.fc37.x86_64.rpm                                                                                                                                     155 kB/s |  12 kB     00:00    
(4/19): libseat-0.7.0-2.fc37.x86_64.rpm                                                                                                                                            367 kB/s |  28 kB     00:00    
(5/19): foot-1.13.1-1.fc37.x86_64.rpm                                                                                                                                              1.0 MB/s | 305 kB     00:00    
(6/19): python3-i3ipc-2.2.1-6.fc37.noarch.rpm                                                                                                                                      918 kB/s |  71 kB     00:00    
(7/19): python3-dbus-next-0.2.3-4.fc37.noarch.rpm                                                                                                                                  1.0 MB/s | 154 kB     00:00    
(8/19): swayfx-0.1-1.fc37.x86_64.rpm                                                                                                                                               547 kB/s | 365 kB     00:00    
(9/19): python3-psutil-5.9.1-1.fc37.x86_64.rpm                                                                                                                                     3.3 MB/s | 271 kB     00:00    
(10/19): python3-tenacity-8.0.1-6.fc37.noarch.rpm                                                                                                                                  787 kB/s |  60 kB     00:00    
(11/19): sway-systemd-0.2.2-2.fc37.noarch.rpm                                                                                                                                      240 kB/s |  18 kB     00:00    
(12/19): sway-1.7-3.fc37.x86_64.rpm                                                                                                                                                4.2 MB/s | 366 kB     00:00    
(13/19): swaybg-1.1.1-2.fc37.x86_64.rpm                                                                                                                                            318 kB/s |  24 kB     00:00    
(14/19): swayidle-1.7.1-2.fc37.x86_64.rpm                                                                                                                                          356 kB/s |  27 kB     00:00    
(15/19): swaylock-1.6-2.fc37.x86_64.rpm                                                                                                                                            545 kB/s |  42 kB     00:00    
(16/19): utf8proc-2.7.0-3.fc37.x86_64.rpm                                                                                                                                          1.0 MB/s |  80 kB     00:00    
(17/19): desktop-backgrounds-compat-37.0.0-4.fc37.noarch.rpm                                                                                                                       118 kB/s | 9.0 kB     00:00    
(18/19): wlroots-0.15.1-4.fc37.x86_64.rpm                                                                                                                                          2.0 MB/s | 319 kB     00:00    
(19/19): python3-xlib-0.31-5.fc37.noarch.rpm                                                                                                                                       788 kB/s | 351 kB     00:00    
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                              984 kB/s | 2.5 MB     00:02     
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  file /etc/sway/config conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/bin/sway conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/bin/swaybar conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/bin/swaymsg conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/bin/swaynag conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man1/sway.1.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man1/swaymsg.1.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man1/swaynag.1.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man5/sway-bar.5.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man5/sway-input.5.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man5/sway-output.5.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man5/sway.5.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man5/swaynag.5.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man7/sway-ipc.7.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
  file /usr/share/man/man7/swaybar-protocol.7.gz conflicts between attempted installs of swayfx-0.1-1.fc37.x86_64 and sway-1.7-3.fc37.x86_64
```

**Comment by ErikReider** [comment]
Hmmm. I'm experiencing the same issue but only when using dnf. Downloading it manually and installing the rpm works as expected. Maybe old cache?

**Comment by AlvaroParker** [comment]
@ErikReider I thought that might be the issue as well so I did a `dnf clean all` and the problem persisted. So just to make sure I installed Fedora on a VM and the problem still persist.

**Comment by ErikReider** [comment]
Yeah, same. I ran:
`rpm -q --queryformat="%{Provides} %{Conflicts}" /var/cache/dnf/copr:copr.fedorainfracloud.org:swayfx:swayfx-b94fc6faf9ea67e1/packages/swayfx-0.1-1.fc37.x86_64.rpm`
Which outputted: `config(swayfx) (none)%`. This is the outdated one.

If I run the same on the latest one, I get `config(swayfx) sway`.

I'll maybe have to change the spec revision?

**Comment by ErikReider** [comment]
@WillPower3309, could  you try bumping
https://github.com/WillPower3309/swayfx/blob/7ccabdad2f0699735a79a001dc1af5a4a46dc5cd/build-scripts/swayfx.rpkg.spec#L11

to 2? Don't really want to create yet another branch for such a small change 🙃

**Comment by WillPower3309** [comment]
done

**Comment by ErikReider** [comment]
Works for me now! Had to disable and enable the copr repo...

`sudo dnf copr disable swayfx/swayfx && sudo copr enable swayfx/swayfx`

```zsh
~ 
❯ sudo dnf install swayfx            
Copr repo for swayfx owned by swayfx                                                                                                18 kB/s | 3.3 kB     00:00    
Copr repo for swayfx owned by swayfx                                                                                                16 kB/s |  11 kB     00:00    
Dependencies resolved.
===================================================================================================================================================================
 Package                         Architecture              Version                           Repository                                                       Size
===================================================================================================================================================================
Installing:
 swayfx                          x86_64                    0.1-2.fc37                        copr:copr.fedorainfracloud.org:swayfx:swayfx                    365 k
Installing weak dependencies:
 sway-systemd                    noarch                    0.2.2-2.fc37                      fedora                                                           18 k

Transaction Summary
===================================================================================================================================================================
Install  2 Packages
```
